version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: iplayed-postgres
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: iplayed
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

